use_frameworks!

target 'EqualableGeneric_Example' do
  pod 'EqualableGeneric', :path => '../'

  target 'EqualableGeneric_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings[‘SWIFT_VERSION’] = ‘4.2’
            config.build_settings[‘GCC_WARN_INHIBIT_ALL_WARNINGS’] = ‘YES’
            if config.build_settings[‘OTHER_SWIFT_FLAGS’].nil?
                config.build_settings[‘OTHER_SWIFT_FLAGS’] = ‘-suppress-warnings’
                else
                config.build_settings[‘OTHER_SWIFT_FLAGS’] += ‘-suppress-warnings’
            end
        end
    end
end
